// AUTO-GENEROVÁNO (scratchpad/gen-flags.mjs) — seznam zemí s českým názvem.
// Vlajky jsou v public/flags/{code}.svg (sada flag-icons, MIT, 4x3). Neupravovat ručně.

export type Country = { code: string; name: string };

export const COUNTRIES: Country[] = [
  { code: "af", name: "Afghánistán" },
  { code: "ax", name: "Ålandy" },
  { code: "al", name: "Albánie" },
  { code: "dz", name: "Alžírsko" },
  { code: "as", name: "Americká Samoa" },
  { code: "vi", name: "Americké Panenské ostrovy" },
  { code: "ad", name: "Andorra" },
  { code: "ao", name: "Angola" },
  { code: "ai", name: "Anguilla" },
  { code: "aq", name: "Antarktida" },
  { code: "ag", name: "Antigua a Barbuda" },
  { code: "ar", name: "Argentina" },
  { code: "am", name: "Arménie" },
  { code: "aw", name: "Aruba" },
  { code: "au", name: "Austrálie" },
  { code: "az", name: "Ázerbájdžán" },
  { code: "bs", name: "Bahamy" },
  { code: "bh", name: "Bahrajn" },
  { code: "bd", name: "Bangladéš" },
  { code: "bb", name: "Barbados" },
  { code: "be", name: "Belgie" },
  { code: "bz", name: "Belize" },
  { code: "by", name: "Bělorusko" },
  { code: "bj", name: "Benin" },
  { code: "bm", name: "Bermudy" },
  { code: "bt", name: "Bhútán" },
  { code: "bo", name: "Bolívie" },
  { code: "bq", name: "Bonaire, Svatý Eustach a Saba" },
  { code: "ba", name: "Bosna a Hercegovina" },
  { code: "bw", name: "Botswana" },
  { code: "bv", name: "Bouvetův ostrov" },
  { code: "br", name: "Brazílie" },
  { code: "io", name: "Britské indickooceánské území" },
  { code: "vg", name: "Britské Panenské ostrovy" },
  { code: "bn", name: "Brunej" },
  { code: "bg", name: "Bulharsko" },
  { code: "bf", name: "Burkina Faso" },
  { code: "bi", name: "Burundi" },
  { code: "ck", name: "Cookovy ostrovy" },
  { code: "cw", name: "Curaçao" },
  { code: "td", name: "Čad" },
  { code: "me", name: "Černá Hora" },
  { code: "cz", name: "Česká republika" },
  { code: "cn", name: "Čína" },
  { code: "dk", name: "Dánsko" },
  { code: "cd", name: "Demokratická republika Kongo" },
  { code: "dm", name: "Dominika" },
  { code: "do", name: "Dominikánská republika" },
  { code: "dj", name: "Džibutsko" },
  { code: "eg", name: "Egypt" },
  { code: "ec", name: "Ekvádor" },
  { code: "er", name: "Eritrea" },
  { code: "ee", name: "Estonsko" },
  { code: "et", name: "Etiopie" },
  { code: "fo", name: "Faerské ostrovy" },
  { code: "fk", name: "Falklandy (Malvíny)" },
  { code: "fj", name: "Fidži" },
  { code: "ph", name: "Filipíny" },
  { code: "fi", name: "Finsko" },
  { code: "fr", name: "Francie" },
  { code: "gf", name: "Francouzská Guyana" },
  { code: "tf", name: "Francouzská jižní a antarktická území" },
  { code: "pf", name: "Francouzská Polynésie" },
  { code: "ga", name: "Gabon" },
  { code: "gm", name: "Gambie" },
  { code: "gh", name: "Ghana" },
  { code: "gi", name: "Gibraltar" },
  { code: "gd", name: "Grenada" },
  { code: "gl", name: "Grónsko" },
  { code: "ge", name: "Gruzie" },
  { code: "gp", name: "Guadeloupe" },
  { code: "gu", name: "Guam" },
  { code: "gt", name: "Guatemala" },
  { code: "gg", name: "Guernsey" },
  { code: "gn", name: "Guinea" },
  { code: "gw", name: "Guinea-Bissau" },
  { code: "gy", name: "Guyana" },
  { code: "ht", name: "Haiti" },
  { code: "hm", name: "Heardův ostrov a McDonaldovy ostrovy" },
  { code: "hn", name: "Honduras" },
  { code: "hk", name: "Hongkong" },
  { code: "cl", name: "Chile" },
  { code: "hr", name: "Chorvatsko" },
  { code: "in", name: "Indie" },
  { code: "id", name: "Indonésie" },
  { code: "iq", name: "Irák" },
  { code: "ir", name: "Írán" },
  { code: "ie", name: "Irsko" },
  { code: "is", name: "Island" },
  { code: "it", name: "Itálie" },
  { code: "il", name: "Izrael" },
  { code: "jm", name: "Jamajka" },
  { code: "jp", name: "Japonsko" },
  { code: "ye", name: "Jemen" },
  { code: "je", name: "Jersey" },
  { code: "za", name: "Jihoafrická republika" },
  { code: "gs", name: "Jižní Georgie a Jižní Sandwichovy ostrovy" },
  { code: "kr", name: "Jižní Korea" },
  { code: "ss", name: "Jižní Súdán" },
  { code: "jo", name: "Jordánsko" },
  { code: "ky", name: "Kajmanské ostrovy" },
  { code: "kh", name: "Kambodža" },
  { code: "cm", name: "Kamerun" },
  { code: "ca", name: "Kanada" },
  { code: "cv", name: "Kapverdy" },
  { code: "qa", name: "Katar" },
  { code: "kz", name: "Kazachstán" },
  { code: "ke", name: "Keňa" },
  { code: "ki", name: "Kiribati" },
  { code: "cc", name: "Kokosové ostrovy" },
  { code: "co", name: "Kolumbie" },
  { code: "km", name: "Komory" },
  { code: "cg", name: "Kongo" },
  { code: "xk", name: "Kosovo" },
  { code: "cr", name: "Kostarika" },
  { code: "cu", name: "Kuba" },
  { code: "kw", name: "Kuvajt" },
  { code: "cy", name: "Kypr" },
  { code: "kg", name: "Kyrgyzstán" },
  { code: "la", name: "Laos" },
  { code: "ls", name: "Lesotho" },
  { code: "lb", name: "Libanon" },
  { code: "lr", name: "Libérie" },
  { code: "ly", name: "Libye" },
  { code: "li", name: "Lichtenštejnsko" },
  { code: "lt", name: "Litva" },
  { code: "lv", name: "Lotyšsko" },
  { code: "lu", name: "Lucembursko" },
  { code: "mo", name: "Macao" },
  { code: "mg", name: "Madagaskar" },
  { code: "hu", name: "Maďarsko" },
  { code: "my", name: "Malajsie" },
  { code: "mw", name: "Malawi" },
  { code: "mv", name: "Maledivy" },
  { code: "ml", name: "Mali" },
  { code: "mt", name: "Malta" },
  { code: "ma", name: "Maroko" },
  { code: "mh", name: "Marshallovy ostrovy" },
  { code: "mq", name: "Martinik" },
  { code: "mu", name: "Mauricius" },
  { code: "mr", name: "Mauritánie" },
  { code: "yt", name: "Mayotte" },
  { code: "um", name: "Menší odlehlé ostrovy USA" },
  { code: "mx", name: "Mexiko" },
  { code: "fm", name: "Mikronésie" },
  { code: "md", name: "Moldavsko" },
  { code: "mc", name: "Monako" },
  { code: "mn", name: "Mongolsko" },
  { code: "ms", name: "Montserrat" },
  { code: "mz", name: "Mosambik" },
  { code: "mm", name: "Myanmar" },
  { code: "na", name: "Namibie" },
  { code: "nr", name: "Nauru" },
  { code: "de", name: "Německo" },
  { code: "np", name: "Nepál" },
  { code: "ne", name: "Niger" },
  { code: "ng", name: "Nigérie" },
  { code: "ni", name: "Nikaragua" },
  { code: "nu", name: "Niue" },
  { code: "nl", name: "Nizozemsko" },
  { code: "nf", name: "Norfolk" },
  { code: "no", name: "Norsko" },
  { code: "nc", name: "Nová Kaledonie" },
  { code: "nz", name: "Nový Zéland" },
  { code: "om", name: "Omán" },
  { code: "im", name: "Ostrov Man" },
  { code: "pk", name: "Pákistán" },
  { code: "pw", name: "Palau" },
  { code: "ps", name: "Palestinská autonomie" },
  { code: "pa", name: "Panama" },
  { code: "pg", name: "Papua-Nová Guinea" },
  { code: "py", name: "Paraguay" },
  { code: "pe", name: "Peru" },
  { code: "pn", name: "Pitcairnovy ostrovy" },
  { code: "ci", name: "Pobřeží slonoviny" },
  { code: "pl", name: "Polsko" },
  { code: "pr", name: "Portoriko" },
  { code: "pt", name: "Portugalsko" },
  { code: "at", name: "Rakousko" },
  { code: "re", name: "Réunion" },
  { code: "gq", name: "Rovníková Guinea" },
  { code: "ro", name: "Rumunsko" },
  { code: "ru", name: "Rusko" },
  { code: "rw", name: "Rwanda" },
  { code: "gr", name: "Řecko" },
  { code: "pm", name: "Saint-Pierre a Miquelon" },
  { code: "sv", name: "Salvador" },
  { code: "ws", name: "Samoa" },
  { code: "sm", name: "San Marino" },
  { code: "sa", name: "Saúdská Arábie" },
  { code: "sn", name: "Senegal" },
  { code: "kp", name: "Severní Korea" },
  { code: "mk", name: "Severní Makedonie" },
  { code: "mp", name: "Severní Mariany" },
  { code: "sc", name: "Seychely" },
  { code: "sl", name: "Sierra Leone" },
  { code: "sg", name: "Singapur" },
  { code: "sk", name: "Slovensko" },
  { code: "si", name: "Slovinsko" },
  { code: "so", name: "Somálsko" },
  { code: "ae", name: "Spojené arabské emiráty" },
  { code: "gb", name: "Spojené království" },
  { code: "us", name: "Spojené státy americké" },
  { code: "rs", name: "Srbsko" },
  { code: "cf", name: "Středoafrická republika" },
  { code: "sd", name: "Súdán" },
  { code: "sr", name: "Surinam" },
  { code: "sh", name: "Svatá Helena, Ascension a Tristan da Cunha" },
  { code: "lc", name: "Svatá Lucie" },
  { code: "bl", name: "Svatý Bartoloměj" },
  { code: "kn", name: "Svatý Kryštof a Nevis" },
  { code: "mf", name: "Svatý Martin (francouzská část)" },
  { code: "sx", name: "Svatý Martin (nizozemská část)" },
  { code: "st", name: "Svatý Tomáš a Princův ostrov" },
  { code: "vc", name: "Svatý Vincenc a Grenadiny" },
  { code: "sz", name: "Svazijsko" },
  { code: "sy", name: "Sýrie" },
  { code: "sb", name: "Šalamounovy ostrovy" },
  { code: "es", name: "Španělsko" },
  { code: "sj", name: "Špicberky a Jan Mayen" },
  { code: "lk", name: "Šrí Lanka" },
  { code: "se", name: "Švédsko" },
  { code: "ch", name: "Švýcarsko" },
  { code: "tj", name: "Tádžikistán" },
  { code: "tz", name: "Tanzanie" },
  { code: "th", name: "Thajsko" },
  { code: "tw", name: "Tchaj-wan" },
  { code: "tg", name: "Togo" },
  { code: "tk", name: "Tokelau" },
  { code: "to", name: "Tonga" },
  { code: "tt", name: "Trinidad a Tobago" },
  { code: "tn", name: "Tunisko" },
  { code: "tr", name: "Turecko" },
  { code: "tm", name: "Turkmenistán" },
  { code: "tc", name: "Turks a Caicos" },
  { code: "tv", name: "Tuvalu" },
  { code: "ug", name: "Uganda" },
  { code: "ua", name: "Ukrajina" },
  { code: "uy", name: "Uruguay" },
  { code: "uz", name: "Uzbekistán" },
  { code: "cx", name: "Vánoční ostrov" },
  { code: "vu", name: "Vanuatu" },
  { code: "va", name: "Vatikán" },
  { code: "ve", name: "Venezuela" },
  { code: "vn", name: "Vietnam" },
  { code: "tl", name: "Východní Timor" },
  { code: "wf", name: "Wallis a Futuna" },
  { code: "zm", name: "Zambie" },
  { code: "eh", name: "Západní Sahara" },
  { code: "zw", name: "Zimbabwe" },
];

export function flagSrc(code: string): string {
  return `/flags/${code}.svg`;
}
